import ProjectGallery from "../components/ProjectGallery";
import CourseBuyButton from "../components/CourseBuyButton";
import {supabase} from "../lib/supabase";
export const revalidate=0;
const nav=["Home","Projects","Services","Courses","Rent","Buy","About","Contact"];
export default async function Home(){
 const [{data:projects},{data:training},{data:ready},{data:settings},{data:rentals}]=await Promise.all([
  supabase.from("projects").select("*,project_images(*)").eq("published",true).order("sort_order"),
  supabase.from("training_examples").select("*").eq("published",true).order("sort_order"),
  supabase.from("ready_made_projects").select("*,ready_made_project_images(*)").eq("published",true).order("sort_order"),
  supabase.from("site_settings").select("*").eq("id","main").maybeSingle(),
  supabase.from("website_offers").select("*,website_offer_images(*)").eq("offer_type","rent").eq("published",true).order("sort_order")
 ]);
 return <><header><div className="brand"><b>AM　ANTONIS MORFITIS</b><small>DIGITAL SOLUTIONS</small></div><nav>{nav.map(x=><a key={x} href={"#"+x.toLowerCase()}><b>{x.toUpperCase()}</b><small>{x==="Home"?"Start here":x==="Projects"?"Explore my work":x==="Services"?"What I can build":x==="Courses"?"Learn & build with me":x==="Rent"?"Rent a website":x==="Buy"?"Own a website":x==="About"?"My story":"Let's work together"}</small></a>)}</nav></header><main>
 <section id="home" className="hero"><div><p>IDEAS • WEBSITES • REAL RESULTS</p><h1>Discipline today.<br/>A better tomorrow.</h1><p>I build digital solutions, e-commerce brands and online systems that create real opportunities.</p><div className="actions"><a href="#projects">View My Work →</a><a href="#contact">Let's Talk →</a></div></div><div className="portrait">{settings?.hero_image_url?<img src={settings.hero_image_url} alt="Antonis Morfitis"/>:"ANTONIS MORFITIS"}</div></section>
 <section id="projects"><p className="eyebrow">SELECTED WORK</p><h2>Projects</h2><div className="grid">{(projects||[]).map((p:any)=>{const imgs=(p.project_images||[]).sort((a:any,b:any)=>a.sort_order-b.sort_order);return <article key={p.id}>{imgs[0]?<img className="offerImage" src={imgs[0].image_url} alt={p.title}/>:<div className="preview">PROJECT PREVIEW</div>}<h3>{p.title}</h3><p>{p.description||p.project_type}</p><a href={"/projects/"+p.slug}>View Project →</a></article>})}</div>{(!projects||projects.length===0)&&<p>Projects will appear here when published from the admin.</p>}</section>
 <section id="services"><p className="eyebrow">WHAT I DO</p><h2>Services</h2><div className="cards">{["Website Development","E-commerce Solutions","Custom Development","AI & Automation","Brand & Strategy","Maintenance & Support"].map(x=><article key={x}><h3>{x}</h3><p>Professional digital solutions built around real business needs.</p></article>)}</div></section>
 <section id="courses" className="trainingSection"><div className="trainingIntro"><p className="eyebrow">PROJECT-BASED TRAINING</p><h2>Learn by building a real project.</h2><p>Personal 1-to-1 guidance from the first idea to a finished launch. Choose the project you want to build and complete it with a clear fixed price.</p></div><div className="trainingGrid">{(training||[]).map((t:any)=><article className="trainingCard" key={t.id}>{t.image_url&&<img className="trainingImage" src={t.image_url} alt={t.title}/>}<div className="trainingBody"><div className="trainingTop"><span>{t.level||t.category}</span><span>{t.duration||"PROJECT-BASED"}</span></div><h3>{t.title}</h3><p className="trainingDesc">{t.description}</p><div className="trainingPrice"><strong>€{(Number(t.price||0)+Number(t.purchase_count||0)).toLocaleString("en-US")}</strong><span>CURRENT PRICE · +€1 AFTER EACH PURCHASE</span></div><div className="courseSalesLive"><b>{Number(t.purchase_count||0)}</b><span>{Number(t.purchase_count||0)===1?"person has":"people have"} purchased this course</span></div>{(t.what_you_learn||[]).length>0&&<div className="trainingBlock"><b>WHAT YOU’LL LEARN</b><ul>{t.what_you_learn.map((x:string)=><li key={x}>{x}</li>)}</ul></div>}{(t.modules||[]).length>0&&<div className="trainingBlock"><b>WHAT YOU CAN BUILD</b><div className="trainingTags">{t.modules.map((x:string)=><span key={x}>{x}</span>)}</div></div>}<div className="trainingActions"><CourseBuyButton courseId={t.id}/><a className="askCourse" href="#contact">Ask a question</a></div></div></article>)}</div>{(!training||training.length===0)&&<p>Programs will appear here when published from the admin.</p>}</section>
 {(ready||[]).length>0&&<section><p className="eyebrow">READY-MADE PROJECTS</p><h2>Ready to Launch</h2><div className="grid">{(ready||[]).map((r:any)=>{const imgs=(r.ready_made_project_images||[]).sort((a:any,b:any)=>a.sort_order-b.sort_order);const gallery=imgs.length?imgs:(r.image_url?[{image_url:r.image_url,alt_text:r.title}]:[]);return <article key={r.id}><ProjectGallery images={gallery} title={r.title}/><h3>{r.title}</h3><p>{r.description}</p>{r.demo_url&&<a href={r.demo_url} target="_blank" rel="noreferrer">Live Demo →</a>}</article>})}</div></section>}
 <section id="rent"><p className="eyebrow">READY-MADE</p><h2>Rent a Website</h2><p>Choose a ready-made website and personalize it with your own brand, services and contact details.</p><div className="grid homeRentalGrid">{(rentals||[]).map((r:any)=>{const imgs=(r.website_offer_images||[]).sort((a:any,b:any)=>a.sort_order-b.sort_order);return <article key={r.id}>{imgs[0]?<img className="offerImage" src={imgs[0].image_url} alt={r.title}/>:<div className="preview">WEBSITE PREVIEW</div>}<div className="offerMeta"><span>{r.category}</span><span>{r.status}</span></div><h3>{r.title}</h3><p>{r.description}</p>{r.price!=null&&<p className="homeRentalPrice">From €{Number(r.price).toFixed(2)} / day</p>}<a href="/rent">View Rental →</a></article>})}</div>{(!rentals||rentals.length===0)&&<p>Rental websites will appear here when published from the admin.</p>}<a className="button rentalExplore" href="/rent">Explore All Rental Websites →</a></section>
 <section id="buy"><p className="eyebrow">OWN IT</p><h2>Buy a Website</h2><p>Purchase a complete website once and make it yours.</p><a className="button" href="/buy">Explore Websites for Sale →</a></section>
 <section id="about"><p className="eyebrow">ABOUT</p><h2>Antonis Morfitis</h2><p>Digital entrepreneur focused on websites, e-commerce, automation and practical online systems.</p></section>
 <section id="contact" className="dark"><p className="eyebrow">CONTACT</p><h2>Let’s Build Something Great</h2><p>New opportunities start with a conversation.</p><a className="lightButton" href="mailto:morfitisantonis@gmail.com">Send a Message →</a></section>
 </main><footer><b>AM　ANTONIS MORFITIS</b><span>© 2026 Antonis Morfitis.</span></footer></>
}