'use client';
import {FormEvent,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Project={id:string;title:string;slug:string;description:string;project_type:string;year:number|null;status:string;role:string;technologies:string[];features:string[];website_url:string;instagram_url:string;facebook_url:string;linkedin_url:string;youtube_url:string;x_url:string;featured:boolean;published:boolean;sort_order:number;project_images?:{id:string;image_url:string;sort_order:number}[]};
const empty:any={title:'',slug:'',description:'',project_type:'Website',year:new Date().getFullYear(),status:'Live',role:'',technologies:[],features:[],website_url:'',instagram_url:'',facebook_url:'',linkedin_url:'',youtube_url:'',x_url:'',featured:false,published:true,sort_order:0};

export default function AdminDashboard(){
 const [session,setSession]=useState<any>(null),[projects,setProjects]=useState<Project[]>([]),[edit,setEdit]=useState<any>(empty),[section,setSection]=useState('Projects'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [email,setEmail]=useState('morfitisantonis@gmail.com'),[password,setPassword]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:s}=supabase.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>s.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const {data}=await supabase.from('projects').select('*,project_images(*)').order('sort_order').order('created_at',{ascending:false});setProjects((data||[]) as Project[])}
 async function login(e:FormEvent){e.preventDefault();setMessage('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}
 async function signup(){setMessage('');const {error}=await supabase.auth.signUp({email,password});setMessage(error?error.message:'Account created. Check your email if confirmation is required, then sign in.')}
 function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const payload={...edit,slug:edit.slug||slugify(edit.title),technologies:Array.isArray(edit.technologies)?edit.technologies:String(edit.technologies||'').split(',').map((x:string)=>x.trim()).filter(Boolean),features:Array.isArray(edit.features)?edit.features:String(edit.features||'').split(',').map((x:string)=>x.trim()).filter(Boolean)};delete payload.project_images;const id=payload.id;delete payload.id;let error:any;if(id)({error}=await supabase.from('projects').update(payload).eq('id',id));else({error}=await supabase.from('projects').insert(payload));setBusy(false);if(error)return setMessage(error.message);setEdit(empty);await load();setMessage('Saved successfully.')}
 async function remove(p:Project){if(!confirm('Delete '+p.title+'?'))return;await supabase.from('projects').delete().eq('id',p.id);if(edit.id===p.id)setEdit(empty);load()}
 async function upload(files:FileList|null){if(!edit.id||!files?.length)return setMessage('Save the project first, then upload images.');setBusy(true);for(const file of Array.from(files)){const path=edit.id+'/'+Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const {error}=await supabase.storage.from('project-media').upload(path,file);if(error){setMessage(error.message);continue}const {data}=supabase.storage.from('project-media').getPublicUrl(path);await supabase.from('project_images').insert({project_id:edit.id,image_url:data.publicUrl,sort_order:(edit.project_images?.length||0)+1})}setBusy(false);const {data}=await supabase.from('projects').select('*,project_images(*)').eq('id',edit.id).single();setEdit(data);load()}
 async function removeImage(id:string){await supabase.from('project_images').delete().eq('id',id);const {data}=await supabase.from('projects').select('*,project_images(*)').eq('id',edit.id).single();setEdit(data);load()}
 if(!session)return <main className="adminLogin"><form onSubmit={login}><div className="adminMark">AM</div><h1>Portfolio Admin</h1><p>Sign in to manage your portfolio.</p><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password"/><button>Sign in</button><button type="button" className="secondary" onClick={signup}>First time? Create admin account</button>{message&&<p className="adminMsg">{message}</p>}</form></main>;
 const nav=['Dashboard','Projects','Training Examples','Ready-Made Projects','Rent Websites','Buy Websites','Purchase Codes'];
 return <div className="adminShell"><aside><div className="adminBrand"><b>AM</b><span>ANTONIS MORFITIS</span></div>{nav.map(n=><button key={n} className={section===n?'active':''} onClick={()=>setSection(n)}>{n}</button>)}<button className="logout" onClick={()=>supabase.auth.signOut()}>Log out</button></aside><main className="adminMain"><header><div><small>PORTFOLIO MANAGEMENT</small><h1>{section}</h1></div><div className="adminUser">Administrator</div></header>
 {section!=='Projects'?<div className="adminEmpty"><h2>{section}</h2><p>This module is separated from Projects and is ready for its own management system.</p></div>:<div className="projectAdmin"><section className="projectList"><div className="panelHead"><h2>All Projects</h2><button onClick={()=>setEdit({...empty})}>+ Add New</button></div>{projects.length===0&&<p>No projects yet. Create your first one.</p>}{projects.map(p=><div className="projectRow" key={p.id}><div><b>{p.title}</b><span>{p.project_type} · {p.published?'Published':'Draft'}</span></div><div><button onClick={()=>setEdit({...p,technologies:(p.technologies||[]).join(', '),features:(p.features||[]).join(', ')})}>Edit</button><button className="danger" onClick={()=>remove(p)}>Delete</button></div></div>)}</section>
 <form className="editor" onSubmit={save}><div className="panelHead"><div><small>{edit.id?'EDIT PROJECT':'NEW PROJECT'}</small><h2>{edit.title||'Project details'}</h2></div><button disabled={busy}>{busy?'Saving…':'Save Project'}</button></div>
 <div className="formGrid"><label>Title<input required value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>Slug<input value={edit.slug} placeholder="automatic-from-title" onChange={e=>setEdit({...edit,slug:e.target.value})}/></label><label className="wide">Description<textarea rows={5} value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><label>Project Type<input value={edit.project_type} onChange={e=>setEdit({...edit,project_type:e.target.value})}/></label><label>Year<input type="number" value={edit.year||''} onChange={e=>setEdit({...edit,year:e.target.value?Number(e.target.value):null})}/></label><label>Status<input value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}/></label><label>My Role<input value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}/></label><label className="wide">Technologies / Services<input value={edit.technologies||''} placeholder="Next.js, Supabase, Stripe" onChange={e=>setEdit({...edit,technologies:e.target.value})}/></label><label className="wide">Key Features<input value={edit.features||''} placeholder="comma separated" onChange={e=>setEdit({...edit,features:e.target.value})}/></label><label className="wide">Website URL<input value={edit.website_url} onChange={e=>setEdit({...edit,website_url:e.target.value})}/></label><label>Instagram<input value={edit.instagram_url} onChange={e=>setEdit({...edit,instagram_url:e.target.value})}/></label><label>Facebook<input value={edit.facebook_url} onChange={e=>setEdit({...edit,facebook_url:e.target.value})}/></label><label>LinkedIn<input value={edit.linkedin_url} onChange={e=>setEdit({...edit,linkedin_url:e.target.value})}/></label><label>YouTube<input value={edit.youtube_url} onChange={e=>setEdit({...edit,youtube_url:e.target.value})}/></label><label>X / Twitter<input value={edit.x_url} onChange={e=>setEdit({...edit,x_url:e.target.value})}/></label><label>Display Order<input type="number" value={edit.sort_order} onChange={e=>setEdit({...edit,sort_order:Number(e.target.value)})}/></label></div>
 <div className="checks"><label><input type="checkbox" checked={edit.featured} onChange={e=>setEdit({...edit,featured:e.target.checked})}/> Featured project</label><label><input type="checkbox" checked={edit.published} onChange={e=>setEdit({...edit,published:e.target.checked})}/> Published</label></div>
 <div className="mediaBox"><h3>Project Gallery</h3><p>Each project keeps its own images. The public slider changes every 3 seconds.</p><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>upload(e.target.files)}/><div className="mediaGrid">{(edit.project_images||[]).sort((a:any,b:any)=>a.sort_order-b.sort_order).map((im:any)=><div key={im.id}><img src={im.image_url} alt="Project"/><button type="button" onClick={()=>removeImage(im.id)}>Remove</button></div>)}</div></div>{message&&<p className="adminMsg">{message}</p>}</form></div>}</main></div>
}